### ISSUE TITLE
incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)

### ISSUE THREAD

**Issue by leoniv** [seattlerb/minitest#649]
### Desc

Hi. It's very very rare case. Error appears in `Minitest::Test#to_s` or in `Minitest::SummaryReporter#aggregated_results` methods. 

Cause of the problem is a exception message returned from WIN32OLE object, if message contain not ASCII chars.

For look at this error should to run test case:

``` ruby
class EncodingCompatibilityErrorTest < Minitest::Test
  def test_this_is_not_ascii_assertion
    assert_equal "ЁЁЁ", "ёёё"
  end

  def test_this_is_non_ascii_failure_message
     fail 'ЁЁЁ'.force_encoding('ASCII-8BIT')
  end
end
```

fail:

```
/home/vlv/.rvm/gems/ruby-2.0.0-p645/gems/minitest-5.9.0/lib/minitest.rb:597:in `join': incompatible character encodings: ASCII-8BIT and UTF-8 (Encoding::CompatibilityError)
        from /home/vlv/.rvm/gems/ruby-2.0.0-p645/gems/minitest-5.9.0/lib/minitest.rb:597:in `aggregated_results'
        from /home/vlv/.rvm/gems/ruby-2.0.0-p645/gems/minitest-5.9.0/lib/minitest.rb:582:in `report'
        from /home/vlv/.rvm/gems/ruby-2.0.0-p645/gems/minitest-5.9.0/lib/minitest.rb:658:in `each'
        from /home/vlv/.rvm/gems/ruby-2.0.0-p645/gems/minitest-5.9.0/lib/minitest.rb:658:in `report'
        from /home/vlv/.rvm/gems/ruby-2.0.0-p645/gems/minitest-5.9.0/lib/minitest.rb:140:in `run'
        from /home/vlv/.rvm/gems/ruby-2.0.0-p645/gems/minitest-5.9.0/lib/minitest.rb:62:in `block in autorun'

```

Failure in the `Minitest::Test#to_s` appear when `self.location` contain non ASCII chars.
### Fix

For fix bug should force encoding exception message. I suppose `Minitest::Test#to_s` is good place for it:

``` ruby
    def to_s # :nodoc:
      return location if passed? and not skipped?

      failures.map { |failure|
#        "#{failure.result_label}:\n#{self.location}:\n#{failure.message}\n"
        "#{failure.result_label}:\n#{self.location}:\n#{failure.message\
           .force_encoding('utf-8')}\n"
      }.join "\n"
    end

```

**Comment by leoniv** [comment]
I'm sorry Minitest::Test#to_s is not a good place for fix it.

I have got error in Minitest::UnexpectedError#message while concatenate backtrace strings with exception message. Example:

```ruby
class EncodingCompatibilityErrorTest < Minitest::Test
  def test_backtrace_содержит_русские_символы
      fail 'ЁЁЁ'.force_encoding('ASCII-8BIT')
  end
end
```
```
/home/vlv/.rvm/gems/ruby-2.0.0-p645/gems/minitest-5.9.0/lib/minitest.rb:721:in `message': incompatible character encodings: ASCII-8BIT and UTF-8 (Encoding::CompatibilityError)
        from /home/vlv/.rvm/gems/ruby-2.0.0-p645/gems/minitest-5.9.0/lib/minitest/test.rb:266:in `block in to_s'
  ```

I have made monkey patch for ```Minitest::UnexpectedError#message``` like:

```ruby
class Minitest::UnexpectedError
  def message # :nodoc:
    bt = Minitest.filter_backtrace(self.backtrace).join "\n    "
    "#{self.exception.class}: #{self.exception.message\
    .force_encoding('utf-8')}\n    #{bt}"
  end
end
```

and it work fine

**Comment by leoniv** [comment]
Thanks!
In `v5.10.3` working without errors.
