### ISSUE TITLE
Extension parameters are not parsed (rails 5)

### ISSUE THREAD

**Issue by KjellMorgenstern** [seattlerb/minitest#684]
When using 'rails test', plugins like for example minitest-profile are still loaded, but the parameters are not parsed, and not shown in the help.

In this example, you can see that the extensions rails, profile and pride are installed.
But neither the profile nor pride command line options show.
```
minitest options:
    -h, --help                       Display this help.
    -s, --seed SEED                  Sets random seed. Also via env. Eg: SEED=n rake
    -v, --verbose                    Verbose. Show progress processing files.
    -n, --name PATTERN               Filter run on /regexp/ or string.
        --exclude PATTERN            Exclude /regexp/ or string from run.

Known extensions: rails, profile, pride

Usage: bin/rails test [options] [files or directories]
You can run a single test by appending a line number to a filename:

    bin/rails test test/models/user_test.rb:27

You can run multiple files and directories at the same time:

    bin/rails test test/controllers test/integration/login_test.rb

By default test failures and errors are reported inline during a run.

Rails options:
    -e, --environment ENV            Run tests in the ENV environment
    -b, --backtrace                  Show the complete backtrace
    -d, --defer-output               Output test failures and errors after the test run
    -f, --fail-fast                  Abort test run on first failure or error
    -c, --[no-]color                 Enable color in the output

```

I think this is related to https://github.com/rails/rails/issues/25046 .
The rails ticket mentions that, since the rails extension has beendmodified to be loaded first, it stops the other plugins from loading their parameters.
Indeed, the error I get when trying to pass a parameter:

```
> rails test --profile
.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.0.1/lib/rails/test_unit/minitest_plugin.rb:57:in `plugin_rails_options': invalid option:--profile (OptionParser::InvalidOption)
        from .rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/minitest-5.10.1/lib/minitest.rb:200:in `block (2 levels) in process_args'
```

I tried with rails 5.0.0.1, 5.0.1, 5.0.2 and 5.1.0RC1, all the same behavior.

Currently the only workaround is to hardcode your wanted options into the extension (don't forget to trigger reloading the gem, for example 'spring stop')

**Comment by zenspider** [comment]
This seems out of my hands.

**Comment by zenspider** [comment]
No response. Closing.
