### ISSUE TITLE
Getting error: aggregated_results: wrong number of arguments (given 1, expected 0)

### ISSUE THREAD

**Issue by jasnow** [seattlerb/minitest#689]
Steps to reproduce:

 1. Run "rake" before upgrade and it is error-free for this repo: 
https://github.com/jasnow/rt_demo_app
      * Have 14 repos with this error, but not all repos.
 2. Run "bundle update minitest" (5.10.1 to 5.10.2) and run "rake" and get this:
```
Finished in 0.316243s, 50.5940 runs/s, 88.5395 assertions/s.
.../.rvm/gems/ruby-2.4.1@ruby2.4.1-rails5.0/gems/railties-5.0.2/lib/rails/test_unit/minitest_plugin.rb:9:in `aggregated_results': wrong number of arguments (given 1, expected 0) (ArgumentError)
	from .../.rvm/gems/ruby-2.4.1@ruby2.4.1-rails5.0/gems/minitest-5.10.2/lib/minitest.rb:597:in `report'
	from .../.rvm/gems/ruby-2.4.1@ruby2.4.1-rails5.0/gems/minitest-5.10.2/lib/minitest.rb:687:in `each'
	from .../.rvm/gems/ruby-2.4.1@ruby2.4.1-rails5.0/gems/minitest-5.10.2/lib/minitest.rb:687:in `report'
	from .../.rvm/gems/ruby-2.4.1@ruby2.4.1-rails5.0/gems/minitest-5.10.2/lib/minitest.rb:141:in `run'
	from .../.rvm/gems/ruby-2.4.1@ruby2.4.1-rails5.0/gems/railties-5.0.2/lib/rails/test_unit/minitest_plugin.rb:72:in `run'
	from .../.rvm/gems/ruby-2.4.1@ruby2.4.1-rails5.0/gems/minitest-5.10.2/lib/minitest.rb:63:in `block in autorun'
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
```

Environment:
 * Mac OS/X 10.12.4
 * Ruby 2.4.1
 * Rails 5.0.2

If you need more, just leave me a comment. Thanks.

**Comment by memiux** [comment]
same

```
$ bin/rails t
Run options: --seed 32310

# Running:

..................................................

Finished in 5.878209s, 8.5060 runs/s, 26.5387 assertions/s.
.../vendor/bundle.dev/ruby/2.4.0/gems/railties-5.1.0/lib/rails/test_unit/minitest_plugin.rb:9:in `aggregated_results': wrong number of arguments (given 1, expected 0) (ArgumentError)
	from .../vendor/bundle.dev/ruby/2.4.0/gems/minitest-5.10.2/lib/minitest.rb:597:in `report'
```

**Comment by zenspider** [comment]
This is a bug in rails and has been fixed:

https://github.com/rails/rails/pull/29022

**Comment by espen** [comment]
Should perhaps minitest 5.10.2 be yanked? I don't blame the minitest authors for this error but given that Rails depends on minitest (minitest (~> 5.1)) and now, due to the popularity of Rails, a lot of devs will encounter this error I think the best thing would be to wait until Rails is released with the bugfix mentioned above. And perhaps release the current minitest as 5.2.0 to avoid the issue for Rails projects and still give others the option of using the latest version of minitest?

**Comment by zenspider** [comment]
No, minitest should not be yanked because of a bug in rails. You can pin in your Gemfile if you want, or wait for a release from the rails team. Talking to @tenderlove about it now, but apparently he's dealing with a dead scooter 🛴 at the moment.

**Comment by espen** [comment]
I'm not worried about my project @zenspider. We both agree that this is a bug in Rails. However my concern is all the newbies using Rails now encountering this issue. I don't think they will know how to pin a minitest version in the Gemfile or find this thread.

Thanks for following up on this. Hopefully @tenderlove's scooter will get a green integration test too.

**Comment by rexmortus** [comment]
Hey everyone! Thanks for jumping on this.

Until there's a new release out, can anyone suggest a path forward here?

**Comment by jasnow** [comment]
@zenspider - Removed all my "pins" during my Rails upgrades. Now no error messages.

**Comment by zenspider** [comment]
Fantastic. Thank you for the update.

**Comment by jasnow** [comment]
@zenspider - You are welcome. Until next time....

**Comment by abebraham** [comment]
Thanks a lot you guys! 

I am just starting out with Rails and this issue was really taking the motivation/fun from learning. All I had to do was bundle update & bundle install with the previously mentioned gem (gem "minitest", "5.10.1")

For those new like myself here you go: 
`group :test do
  gem 'rails-controller-testing', '0.1.1'
  gem 'minitest-reporters',       '1.1.9'
  gem 'guard',                    '2.13.0'
  gem 'guard-minitest',           '2.4.4'
  gem "minitest",                 '5.10.1'
end`

**Comment by zenspider** [comment]
@abebraham you don't have to do that now. you can update rails to 5.0.3.

**Comment by mixflame** [comment]
still an issue in rails 5.1.0 it seems...
