### ISSUE TITLE
Stubs not working nondeterministically - TravisCI

### ISSUE THREAD

**Issue by Shockolate** [seattlerb/minitest#698]
When unit testing my gem in Travis, I occasionally get `NoMethodError`s on my stubs. This happens non-deterministically, and is hard for me to reproduce. This has ocurred in all ruby versions that I specify Travis to build.

[Link to Gem](https://github.com/Cimpress-MCP/LambdaWrap)
[Link to example travis build](https://travis-ci.org/Cimpress-MCP/LambdaWrap/builds/235364859)

Error:
```ruby
** Invoke unit_test (first_time)
** Execute unit_test
/home/travis/.rvm/rubies/ruby-2.4.1/bin/ruby -I"lib" -I"/home/travis/build/Cimpress-MCP/LambdaWrap/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib" "/home/travis/build/Cimpress-MCP/LambdaWrap/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/rake_test_loader.rb" "test/unit/test_api_gateway_manager.rb" "test/unit/test_api_manager.rb" "test/unit/test_aws_service.rb" "test/unit/test_dynamo_db_manager.rb" "test/unit/test_environment.rb" "test/unit/test_lambda_manager.rb" --pride
Started with run options --pride --seed 12597
ERROR["test_0004_ should create a new function and new alias successfully.", #<Class:0x0000000126e8b8>, 0.10417573399899993]
 test_0004_ should create a new function and new alias successfully.#LambdaWrap::Lambda:: when deploying the Lambda  (0.10s)
NoMethodError:         NoMethodError: undefined method `read' for nil:NilClass
            /home/travis/build/Cimpress-MCP/LambdaWrap/vendor/bundle/ruby/2.4.0/gems/aws-sdk-core-2.9.22/lib/aws-sdk-core/json.rb:32:in `block in load_file'
```

Unit Test:
```ruby
      it ' should update function code, configuration and create a new alias successfully. ' do
        File.stub :exist?, true do
          File.stub(:open, FileOpenDouble.new) do
            lambda_client = Aws::Lambda::Client.new(
              stub_responses: {
                get_function: { configuration: { version: '3' } },
                update_function_configuration: { version: '3' },
                update_function_code: { version: '4' },
                list_aliases: { aliases: [{ name: 'WrongName' }] },
                create_alias: { name: 'UnitTestingEnvironmentValid' }
              }
            )
            lambda_valid.deploy(environment_valid, lambda_client, 'eu-west-1').must_equal(true)
          end
        end
      end

    class FileOpenDouble
      def initialize
        super
      end

      def read
        'BLOB DATA'
      end
    end
```

Unit under test:
```ruby
    def create_lambda
      puts "Creating New Lambda Function: #{@lambda_name}...."
      puts "Runtime Engine: #{@runtime}, Timeout: #{@timeout}, Memory Size: #{@memory_size}."

      lambda_version = @client.create_function(
        function_name: @lambda_name, runtime: @runtime, role: @role_arn, handler: @handler,
        code: { zip_file: File.open(@path_to_zip_file, 'rb').read }, description: @description, timeout: @timeout,
        memory_size: @memory_size, vpc_config: @vpc_configuration, publish: true
      ).version
      puts "Successfully created Lambda: #{@lambda_name}!"
      lambda_version
    end
```

**Comment by zenspider** [comment]
```
lib/lambda_wrap/api_gateway_manager.rb:1:1: C: Carriage return character detected.
```

clearly it is the carriage return. 😛 

```
--seed 4992
```

OK. Since you have a seed that DOES see this problem, can you reproduce using that seed? If it only happens on travis, you can set via an environment variable `SEED=4992`.

**Comment by zenspider** [comment]
Please stop using minitest-reporters. This output is worse than useless:

```
ERROR["test_0005_ should update function code, configuration and create a new alias successfully. ", #<Class:0x0000000221a668>, 0.1982310810017225]
 test_0005_ should update function code, configuration and create a new alias successfully. #LambdaWrap::Lambda:: when deploying the Lambda  (0.20s)
NoMethodError:         NoMethodError: undefined method `read' for nil:NilClass
            /home/travis/build/Cimpress-MCP/LambdaWrap/vendor/bundle/ruby/2.3.0/gems/aws-sdk-core-2.9.22/lib/aws-sdk-core/json.rb:32:in `block in load_file'
```

I can't tell where the test is at all.

**Comment by Shockolate** [comment]
@zenspider Any reporter suggestions?

**Comment by Shockolate** [comment]
It is reproducible when specifying: `--seed 4992` both on my Dev Machine, and in travis.
[Pull Request that triggered Travis](https://github.com/Cimpress-MCP/LambdaWrap/pull/48)
[Travis Build](https://travis-ci.org/Cimpress-MCP/LambdaWrap/builds/235440282?utm_source=github_status)
[Test that's erroring](https://github.com/Shockolate/LambdaWrap/blob/minitest_stub_debug/test/unit/test_lambda_manager.rb#L191)
[Unit under test that's throwing the error](https://github.com/Shockolate/LambdaWrap/blob/minitest_stub_debug/lib/lambda_wrap/lambda_manager.rb#L216)

**Comment by zenspider** [comment]
Yes. I've found that it reproduces with that seed. Just as important, it always passes with a seed of 42:

```
10619 % minitest -Ilib:~/.gem/repos/minitest698/gems/minitest-5.10.2/lib/ test/unit --seed 42
Run options: --seed 42

# Running:

...........................................................................

Finished in 0.716615s, 104.6587 runs/s, 228.8537 assertions/s.

75 runs, 164 assertions, 0 failures, 0 errors, 0 skips
```

BUT! It fails with that seed if you run only one of the failures:

```
% minitest -Ilib:~/.gem/repos/minitest698/gems/minitest-5.10.2/lib/ test/unit --seed 42 -n "/^(?:LambdaWrap::Lambda:: when deploying the Lambda #(?:test_0004_ should create a new function and new alias successfully.))$/"
Run options: --seed 42 -n "/^(?:LambdaWrap::Lambda:: when deploying the Lambda #(?:test_0004_ should create a new function and new alias successfully.))$/"

# Running:

E

Finished in 0.170888s, 5.8518 runs/s, 0.0000 assertions/s.

  1) Error:
LambdaWrap::Lambda:: when deploying the Lambda #test_0004_ should create a new function and new alias successfully.:
NoMethodError: undefined method `read' for nil:NilClass
    /Users/ryan/.gem/repos/minitest698/gems/aws-sdk-core-2.9.23/lib/aws-sdk-core/json.rb:32:in `block in load_file'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

This is something that my gem `minitest-bisect` does NOT deal with at this point: finding the test that makes a failure pass. I'm gonna think about that one for a bit and see how I can modify minitest-bisect to make this problem much easier to diagnose.

 That said, there are 50 tests that are culprits:

```
LambdaWrap::ApiGateway:: when constructing the API Gateway #test_0001_ should create successfully with all valid values given. = 0.01 s = .
LambdaWrap::ApiGateway:: when constructing the API Gateway #test_0002_ should throw an error if the swagger file doesnt exist. = 0.00 s = .
LambdaWrap::Lambda:: when deleting the Lambda #test_0002_ should successfully delete the Lambda if it doesnt exist.  = 0.17 s = .
LambdaWrap::Lambda:: when deleting the Lambda #test_0001_ successfully delete the function.  = 0.01 s = .
LambdaWrap::API:: when adding a table #test_0004_ should not add non tables.  = 0.17 s = .
LambdaWrap::API:: when adding a table #test_0002_ should add an array successfully.  = 0.01 s = .
LambdaWrap::API:: when adding a table #test_0001_ should add one successfully.  = 0.00 s = .
LambdaWrap::API:: when adding a table #test_0003_ should add a splat successfully.  = 0.00 s = .
LambdaWrap::API:: when deploying #test_0002_ should throw an error if an Environment is not given.  = 0.00 s = .
LambdaWrap::API:: when deploying #test_0003_ should deploy all services successfully.  = 0.00 s = .
LambdaWrap::API:: when deploying #test_0001_ should not do anything if no Services have been added.  = 0.00 s = .
LambdaWrap::DynamoTable:: when deleting a DynamoTable #test_0001_ should return successfully if there is no table to delete.  = 0.01 s = .
LambdaWrap::DynamoTable:: when deleting a DynamoTable #test_0002_ should return successfully and delete 1 table if not appending environment name.  = 0.01 s = .
LambdaWrap::DynamoTable:: when deleting a DynamoTable #test_0003_ should return successfully and delete 3 tables if appending environment name.  = 0.01 s = .
LambdaWrap::DynamoTable:: when deploying a DynamoTable #test_0002_ should return successfully when creating the table for the first time.  = 0.01 s = .
LambdaWrap::DynamoTable:: when deploying a DynamoTable #test_0003_ should return successfully when updating a table with new Global Index, an Update to a Global Index, \
\        and Deleting a Global Index.  = 0.09 s = .
LambdaWrap::DynamoTable:: when deploying a DynamoTable #test_0001_ should return successfully with no necessary updates.  = 0.01 s = .
LambdaWrap::API:: when constructiong an API object #test_0006_ should throw an error if the credentials arent given (access key) = 0.00 s = .
LambdaWrap::API:: when constructiong an API object #test_0001_ should return successfully with stubbed options.  = 0.00 s = .
LambdaWrap::API:: when constructiong an API object #test_0002_ should return successfully with valid options passed in = 0.00 s = .
LambdaWrap::API:: when constructiong an API object #test_0003_ should return successfully with valid Environment Variables (first conditions...). = 0.00 s = .
LambdaWrap::API:: when constructiong an API object #test_0004_ should return successfully with valid Environment Variables (second conditions...). = 0.00 s = .
LambdaWrap::API:: when constructiong an API object #test_0005_ should return successfully with valid Environment Variables (third conditions...). = 0.01 s = .
LambdaWrap::API:: when constructiong an API object #test_0007_ should throw an error if the credentials arent given (secret key) = 0.00 s = .
LambdaWrap::API:: when constructiong an API object #test_0008_ should throw an error if the region is not given = 0.00 s = .
LambdaWrap::API:: when deleting #test_0001_ should not do anything if no services have been added.  = 0.00 s = .
LambdaWrap::API:: when deleting #test_0002_ should delete all services successfully.  = 0.00 s = .
LambdaWrap::Lambda:: when tearing-down the Lambda #test_0001_ should throw an error a LambdaWrap::Environment is not given.  = 0.00 s = .
LambdaWrap::Lambda:: when tearing-down the Lambda #test_0003_ should delete the alias successfully and delete unused versions.  = 0.01 s = .
LambdaWrap::Lambda:: when tearing-down the Lambda #test_0002_ should delete the alias successfully.  = 0.00 s = .
LambdaWrap::API:: when tearing-down #test_0002_ should teardown all services successfully.  = 0.00 s = .
LambdaWrap::API:: when tearing-down #test_0001_ shoud not do anything if no Services have been added.  = 0.00 s = .
LambdaWrap::DynamoTable:: when constructing a DynamoTable #test_0005_ should throw an error if too many GlobalSecondaryIndexes are Given.  = 0.00 s = .
LambdaWrap::DynamoTable:: when constructing a DynamoTable #test_0003_ should throw an error if table name isnt given.  = 0.00 s = .
LambdaWrap::DynamoTable:: when constructing a DynamoTable #test_0004_ should throw an error if too many LocalSecondaryIndexes are given.  = 0.00 s = .
LambdaWrap::DynamoTable:: when constructing a DynamoTable #test_0006_ should throw an error if an Index's key_schema is not defined in the attribute_definitions  = 0.00 s = .
LambdaWrap::DynamoTable:: when constructing a DynamoTable #test_0007_ should throw an error if the provisioned throughput of the table or indexes are invalid.  = 0.00 s = .
LambdaWrap::DynamoTable:: when constructing a DynamoTable #test_0001_ should return successfully with valid supplied arguments.  = 0.00 s = .
LambdaWrap::DynamoTable:: when constructing a DynamoTable #test_0002_ should return successfully with minimal arguments.  = 0.00 s = .
LambdaWrap::API:: when adding lambda #test_0001_ should add one successfully.  = 0.00 s = .
LambdaWrap::API:: when adding lambda #test_0003_ should add a splat successfully.  = 0.00 s = .
LambdaWrap::API:: when adding lambda #test_0004_ should not add non Lambdas.  = 0.00 s = .
LambdaWrap::API:: when adding lambda #test_0002_ should add an array successfully.  = 0.00 s = .
LambdaWrap::Environment:: When constructing the environment #test_0003_ should throw an error with bad values.  = 0.00 s = .
LambdaWrap::Environment:: When constructing the environment #test_0002_ should be constructed successfully when supplying some values.  = 0.00 s = .
LambdaWrap::Environment:: When constructing the environment #test_0001_ should be constructed successfully when supplying all values.  = 0.00 s = .
LambdaWrap::Lambda:: when deploying the Lambda #test_0006_ should update function code, configuration, and alias successfully. = 0.01 s = .
LambdaWrap::Lambda:: when deploying the Lambda #test_0003_ should throw an error if the zip file does not exist.  = 0.00 s = .
LambdaWrap::Lambda:: when deploying the Lambda #test_0005_ should update function code, configuration and create a new alias successfully.  = 0.01 s = .
LambdaWrap::Lambda:: when deploying the Lambda #test_0004_ should create a new function and new alias successfully. = 0.01 s = .
```

the last one is the one that fails when run in isolation. Basically, that test never really worked. The question is why. Something running before it causes it to pass regardless.

**Comment by zenspider** [comment]
I wrote a very quick script to try to find individual tests that will cause this one to pass:

```
minitest -Ilib test/unit --seed 42 -n "/(?-mix:LambdaWrap::Lambda::\ when\ deleting\ the\ Lambda\ \#test_0002_\ should\ successfully\ delete\ the\ Lambda\ if\ it\ doesnt\ exist\.\ |LambdaWrap::Lambda::\ when\ deploying\ the\ Lambda\ \#test_0004_\ should\ create\ a\ new\ function\ and\ new\ alias\ successfully\.)/"
minitest -Ilib test/unit --seed 42 -n "/(?-mix:LambdaWrap::Lambda::\ when\ deleting\ the\ Lambda\ \#test_0001_\ successfully\ delete\ the\ function\.\ |LambdaWrap::Lambda::\ when\ deploying\ the\ Lambda\ \#test_0004_\ should\ create\ a\ new\ function\ and\ new\ alias\ successfully\.)/"
minitest -Ilib test/unit --seed 42 -n "/(?-mix:LambdaWrap::DynamoTable::\ when\ deleting\ a\ DynamoTable\ \#test_0001_\ should\ return\ successfully\ if\ there\ is\ no\ table\ to\ delete\.\ |LambdaWrap::Lambda::\ when\ deploying\ the\ Lambda\ \#test_0004_\ should\ create\ a\ new\ function\ and\ new\ alias\ successfully\.)/"
minitest -Ilib test/unit --seed 42 -n "/(?-mix:LambdaWrap::DynamoTable::\ when\ deleting\ a\ DynamoTable\ \#test_0002_\ should\ return\ successfully\ and\ delete\ 1\ table\ if\ not\ appending\ environment\ name\.\ |LambdaWrap::Lambda::\ when\ deploying\ the\ Lambda\ \#test_0004_\ should\ create\ a\ new\ function\ and\ new\ alias\ successfully\.)/"
minitest -Ilib test/unit --seed 42 -n "/(?-mix:LambdaWrap::DynamoTable::\ when\ deleting\ a\ DynamoTable\ \#test_0003_\ should\ return\ successfully\ and\ delete\ 3\ tables\ if\ appending\ environment\ name\.\ |LambdaWrap::Lambda::\ when\ deploying\ the\ Lambda\ \#test_0004_\ should\ create\ a\ new\ function\ and\ new\ alias\ successfully\.)/"
minitest -Ilib test/unit --seed 42 -n "/(?-mix:LambdaWrap::DynamoTable::\ when\ deploying\ a\ DynamoTable\ \#test_0002_\ should\ return\ successfully\ when\ creating\ the\ table\ for\ the\ first\ time\.\ |LambdaWrap::Lambda::\ when\ deploying\ the\ Lambda\ \#test_0004_\ should\ create\ a\ new\ function\ and\ new\ alias\ successfully\.)/"
minitest -Ilib test/unit --seed 42 -n "/(?-mix:LambdaWrap::DynamoTable::\ when\ deploying\ a\ DynamoTable\ \#test_0003_\ should\ return\ successfully\ when\ updating\ a\ table\ with\ new\ Global\ Index,\ an\ Update\ to\ a\ Global\ Index,\ |LambdaWrap::Lambda::\ when\ deploying\ the\ Lambda\ \#test_0004_\ should\ create\ a\ new\ function\ and\ new\ alias\ successfully\.)/"
minitest -Ilib test/unit --seed 42 -n "/(?-mix:\ \ \ \ \ \ \ \ and\ Deleting\ a\ Global\ Index\.\ |LambdaWrap::Lambda::\ when\ deploying\ the\ Lambda\ \#test_0004_\ should\ create\ a\ new\ function\ and\ new\ alias\ successfully\.)/"
minitest -Ilib test/unit --seed 42 -n "/(?-mix:LambdaWrap::DynamoTable::\ when\ deploying\ a\ DynamoTable\ \#test_0001_\ should\ return\ successfully\ with\ no\ necessary\ updates\.\ |LambdaWrap::Lambda::\ when\ deploying\ the\ Lambda\ \#test_0004_\ should\ create\ a\ new\ function\ and\ new\ alias\ successfully\.)/"
minitest -Ilib test/unit --seed 42 -n "/(?-mix:LambdaWrap::Lambda::\ when\ tearing\-down\ the\ Lambda\ \#test_0003_\ should\ delete\ the\ alias\ successfully\ and\ delete\ unused\ versions\.\ |LambdaWrap::Lambda::\ when\ deploying\ the\ Lambda\ \#test_0004_\ should\ create\ a\ new\ function\ and\ new\ alias\ successfully\.)/"
minitest -Ilib test/unit --seed 42 -n "/(?-mix:LambdaWrap::Lambda::\ when\ tearing\-down\ the\ Lambda\ \#test_0002_\ should\ delete\ the\ alias\ successfully\.\ |LambdaWrap::Lambda::\ when\ deploying\ the\ Lambda\ \#test_0004_\ should\ create\ a\ new\ function\ and\ new\ alias\ successfully\.)/"
minitest -Ilib test/unit --seed 42 -n "/(?-mix:LambdaWrap::Lambda::\ when\ deploying\ the\ Lambda\ \#test_0003_\ should\ throw\ an\ error\ if\ the\ zip\ file\ does\ not\ exist\.\ |LambdaWrap::Lambda::\ when\ deploying\ the\ Lambda\ \#test_0004_\ should\ create\ a\ new\ function\ and\ new\ alias\ successfully\.)/"
```

**Comment by zenspider** [comment]
Sure enough... taking the first one, the deletion test runs before the creation/alias test. If I copy its body into the failing test then it passes:

```ruby
      it ' should create a new function and new alias successfully.' do
        lambda_client = Aws::Lambda::Client.new(
          stub_responses: {
            get_function: { configuration: {} },
            delete_function: {}
          }
        )
        lambda_valid.delete(lambda_client, 'eu-west-1').must_equal(true)

        # Stubs exist?
        ::File.stub :exist?, true do
          ::File.stub(:open, FileOpenDouble.new) do
            lambda_client = Aws::Lambda::Client.new(
              stub_responses: {
                get_function: 'ResourceNotFoundException',
                create_function: { version: '1' },
                list_aliases: { aliases: [{ name: 'WrongName' }] },
                create_alias: { name: 'UnitTestingEnvironmentValid' }
              }
            )
            lambda_valid.deploy(environment_valid, lambda_client, 'eu-west-1').must_equal(true)
          end
        end
      end
```

**Comment by zenspider** [comment]
That's as far as I can/will take it ATM... Seattle.rb is about to start. The question is: what side effects does `lambda_valid.delete` have that causes the test to pass?

**Comment by zenspider** [comment]
One more:

When it passes it is using the stub here:

```
READ from /private/tmp/LambdaWrap/lib/lambda_wrap/lambda_manager.rb:188:in `create_lambda'
```

When it fails, it isn't hitting the stub and instead fails inside the aws client on nil. Not sure why.

So... this isn't stubs so much as it is unknown side effects. 

That said, I think that you're testing too deep. Your library is wrapping the AWS library, not testing it.

**Comment by Shockolate** [comment]
First:
sorry for the delay in responding, I'm on the east coast so I wasn't able to stay current with your posts & massive help :smile:

Second:
> That said, I think that you're testing too deep. Your library is wrapping the AWS library, not testing it.
I don't think I'm entirely sure what you mean. Would you suggest any resources for me to consume that can help me with my testing strategies? I've been following the [don't mock what you don't own](https://github.com/mockito/mockito/wiki/How-to-write-good-tests) philosophy of ruby. As you can probably tell, I'm still somewhat of a novice of ruby.

Third:
If this is a testing strategy problem, and not a `Minitest` problem, should I close this ticket?

**Comment by Shockolate** [comment]
@zenspider 
Followed your lead on the side effects of the AWS Lambda client. Dived deep into the [AWS SDK](https://github.com/aws/aws-sdk-ruby), and the base class [Seahorse](https://github.com/awslabs/railsconf2013-tech-demo). Seahorse is is a gem that allows one to create clients with a DSL...

I pulled all of the Hash Parameters for each  AWS client function invocation, and the tests all pass regardless of seed! I suspect the `Seahorse` client construction caused side effects.

I recommend all other consumers of the Ruby AWS SDK to pull their Hash Parameters out to a variable and pass that variable in (as shown in [this pull request](https://github.com/Cimpress-MCP/LambdaWrap/pull/48)).
