### ISSUE TITLE
Allow to receive arbitrary arguments in `aggregated_results`

### ISSUE THREAD

**Issue by Baozi2** [seattlerb/minitest#734]
When run rails test runner with minitest 5.11.1, the following error occurred.

```
Finished in 0.506916s, 13.8090 runs/s, 17.7544 assertions/s.
/Users/shisi/.rvm/gems/ruby-2.4.3/gems/railties-5.1.0/lib/rails/test_unit/minitest_plugin.rb:9:in `aggregated_results': wrong number of arguments (given 1, expected 0) (ArgumentError)
	from /Users/shisi/.rvm/gems/ruby-2.4.3/gems/minitest-5.11.1/lib/minitest.rb:701:in `report'
	from /Users/shisi/.rvm/gems/ruby-2.4.3/gems/minitest-5.11.1/lib/minitest.rb:791:in `each'
	from /Users/shisi/.rvm/gems/ruby-2.4.3/gems/minitest-5.11.1/lib/minitest.rb:791:in `report'
	from /Users/shisi/.rvm/gems/ruby-2.4.3/gems/minitest-5.11.1/lib/minitest.rb:141:in `run'
	from /Users/shisi/.rvm/gems/ruby-2.4.3/gems/railties-5.1.0/lib/rails/test_unit/minitest_plugin.rb:77:in `run'
	from /Users/shisi/.rvm/gems/ruby-2.4.3/gems/minitest-5.11.1/lib/minitest.rb:63:in `block in autorun'
	from /Users/shisi/.rvm/gems/ruby-2.4.3/gems/spring-2.0.2/lib/spring/application.rb:171:in `fork'
	from /Users/shisi/.rvm/gems/ruby-2.4.3/gems/spring-2.0.2/lib/spring/application.rb:171:in `serve'
	from /Users/shisi/.rvm/gems/ruby-2.4.3/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
	from /Users/shisi/.rvm/gems/ruby-2.4.3/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
	from /Users/shisi/.rvm/gems/ruby-2.4.3/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
	from /Users/shisi/.rvm/gems/ruby-2.4.3/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/shisi/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/shisi/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'

rails 5.1
minitest 5.11.1
Mac os 10.13.2
```
I find this occurred in rails 5.1

**Comment by zenspider** [comment]
This is a bug in railties and is fixed in 5.1.1. Given the nature of dot-zero releases. I highly recommend you update your rails install to at least 5.1.3.

https://github.com/rails/rails/blob/5-1-stable/railties/CHANGELOG.md
