### ISSUE TITLE
Tests fail in verbose

### ISSUE THREAD

**Issue by utilum** [seattlerb/minitest#743]
I don't know if this is related to #737 being fixed, but things just got worse:

```
$ $ rake TESTOPTS="-v" 
~/.rbenv/versions/2.5.0/bin/ruby -w -Ilib:bin:test:. -e 'require "rubygems"; require "minitest/autorun"; require "test/minitest/test_minitest_test.rb"; require "test/minitest/test_minitest_spec.rb"; require "test/minitest/test_minitest_benchmark.rb"; require "test/minitest/test_minitest_test.rb"; require "test/minitest/test_minitest_mock.rb"; require "test/minitest/test_minitest_reporter.rb"; require "test/minitest/test_minitest_spec.rb"' -- -v
Run options: -v --seed 62957

# Running:

# ...

Skipped:
TestMinitestStub#test_stub_value_block_6 [~/code/minitest/test/minitest/test_minitest_mock.rb:861]:
not yet

#<Thread:0x00005626fabe5380@~/code/minitest/lib/minitest/parallel.rb:28 run> terminated with exception (report_on_exception is true):
~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.2.0.beta2/lib/rails/test_unit/reporter.rb:71:in `method': undefined method `test_stub_value_block_6' for class `Minitest::Result' (NameError)
	from ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.2.0.beta2/lib/rails/test_unit/reporter.rb:71:in `format_rerun_snippet'
	from ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.2.0.beta2/lib/rails/test_unit/reporter.rb:24:in `record'
	from ~/code/minitest/lib/minitest.rb:803:in `block in record'
	from ~/code/minitest/lib/minitest.rb:802:in `each'
	from ~/code/minitest/lib/minitest.rb:802:in `record'
	from ~/code/minitest/lib/minitest/parallel.rb:34:in `block (3 levels) in start'
	from ~/.rbenv/versions/2.5.0/lib/ruby/2.5.0/mutex_m.rb:71:in `synchronize'
	from ~/.rbenv/versions/2.5.0/lib/ruby/2.5.0/mutex_m.rb:71:in `mu_synchronize'
	from ~/code/minitest/lib/minitest/parallel.rb:34:in `block (2 levels) in start'
Minitest::Result#test_stub_value_block_5 = 0.00 s = .
Minitest::Result#test_stub_value_block_args_6_2 = 0.00 s = S


~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.2.0.beta2/lib/rails/test_unit/reporter.rb:71:in `method': undefined method `test_stub_value_block_6' for class `Minitest::Result' (NameError)
	from ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.2.0.beta2/lib/rails/test_unit/reporter.rb:71:in `format_rerun_snippet'
	from ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.2.0.beta2/lib/rails/test_unit/reporter.rb:24:in `record'
	from ~/code/minitest/lib/minitest.rb:803:in `block in record'
	from ~/code/minitest/lib/minitest.rb:802:in `each'
	from ~/code/minitest/lib/minitest.rb:802:in `record'
	from ~/code/minitest/lib/minitest/parallel.rb:34:in `block (3 levels) in start'
	from ~/.rbenv/versions/2.5.0/lib/ruby/2.5.0/mutex_m.rb:71:in `synchronize'
	from ~/.rbenv/versions/2.5.0/lib/ruby/2.5.0/mutex_m.rb:71:in `mu_synchronize'
	from ~/code/minitest/lib/minitest/parallel.rb:34:in `block (2 levels) in start'
rake aborted!
Command failed with status (1): [~/.rbenv/versions/2.5.0/bin/ruby -w...]

Tasks: TOP => default => test
(See full trace by running task with --trace)
```

**Comment by zenspider** [comment]
Looks like rails to me...

**Comment by utilum** [comment]
You are both correct. Thank you.
