### ISSUE TITLE
Report on failure or error

### ISSUE THREAD

**Issue by rhuanbarreto** [seattlerb/minitest#746]
How can I enable reporting on failure and error on the tests?

In [RailsGuides](http://guides.rubyonrails.org/testing.html#your-first-failing-test) they show the results on the example.

```
$ bin/rails test test/models/article_test.rb:6
Run options: --seed 44656
 
# Running:
 
F
 
Failure:
ArticleTest#test_should_not_save_article_without_title [/path/to/blog/test/models/article_test.rb:6]:
Expected true to be nil or false
 
 
bin/rails test test/models/article_test.rb:6
 
 
 
Finished in 0.023918s, 41.8090 runs/s, 41.8090 assertions/s.
 
1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
```

But when I run, the following error appears.

```
$ rails test test/integration/ip_controller_test.rb 
Emptying /Users/rhuan/rails-apps/vts/test/reports
Run options: --seed 62241

# Running:

.F

Failure:
IPControllerTest#test_fail [/Users/rhuan/rails-apps/vts/test/integration/ip_controller_test.rb:10]:
Expected nil to be truthy.


/Users/rhuan/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/railties-5.0.6/lib/rails/test_unit/reporter.rb:70:in `method': undefined method `test_fail' for class `Minitest::Result' (NameError)
	from /Users/rhuan/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/railties-5.0.6/lib/rails/test_unit/reporter.rb:70:in `format_rerun_snippet'
	from /Users/rhuan/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/railties-5.0.6/lib/rails/test_unit/reporter.rb:23:in `record'
	from /Users/rhuan/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/minitest-5.11.3/lib/minitest.rb:803:in `block in record'
	from /Users/rhuan/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/minitest-5.11.3/lib/minitest.rb:802:in `each'
	from /Users/rhuan/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/minitest-5.11.3/lib/minitest.rb:802:in `record'
	from /Users/rhuan/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/minitest-5.11.3/lib/minitest.rb:334:in `run_one_method'
	from /Users/rhuan/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/minitest-5.11.3/lib/minitest.rb:321:in `block (2 levels) in run'
	from /Users/rhuan/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/minitest-5.11.3/lib/minitest.rb:320:in `each'
	from /Users/rhuan/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/minitest-5.11.3/lib/minitest.rb:320:in `block in run'
	from /Users/rhuan/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/minitest-5.11.3/lib/minitest.rb:360:in `on_signal'
	from /Users/rhuan/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/minitest-5.11.3/lib/minitest.rb:347:in `with_info_handler'
	from /Users/rhuan/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/minitest-5.11.3/lib/minitest.rb:319:in `run'
	from /Users/rhuan/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/railties-5.0.6/lib/rails/test_unit/line_filtering.rb:9:in `run'
	from /Users/rhuan/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/minitest-5.11.3/lib/minitest.rb:159:in `block in __run'
	from /Users/rhuan/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/minitest-5.11.3/lib/minitest.rb:159:in `map'
	from /Users/rhuan/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/minitest-5.11.3/lib/minitest.rb:159:in `__run'
	from /Users/rhuan/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/minitest-5.11.3/lib/minitest.rb:136:in `run'
	from /Users/rhuan/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/minitest-5.11.3/lib/minitest.rb:63:in `block in autorun'
```

**Comment by utilum** [comment]
Your output _does_ report the failure... followed by a trace. What are you missing?

**Comment by rhuanbarreto** [comment]
Investigating better is the same problem as #730.
But they released a fix for Rails 5.1 (in rails/rails#31624) not 5.0.
Could you add a fix to it in Rails 5.0?
For now I locked the Minitest version to 5.10.3 and it works well.

**Comment by utilum** [comment]
For a fix in Rails 5.1 to be backported to Rails 5.0 you'd need to ask on Rails...

**Comment by utilum** [comment]
Which I see that you already have done...

**Comment by zenspider** [comment]
Close?

**Comment by rhuanbarreto** [comment]
Yes.

Just to leave here how I solved the problem, I needed to pin the minitest version in order to work, once the rails team [don't publish bugfixes to old branches](http://guides.rubyonrails.org/maintenance_policy.html) (Is rails 5.0 really different that they can't maintain it? They rejected my pull request to 5.0 branch!)

So you need to put on your gemfile:
```ruby
gem 'minitest', '5.10.3'
```

Hope that this will help someone.
