### ISSUE TITLE
Crash triggered from minitest in Ruby 2.4 and 2.5

### ISSUE THREAD

**Issue by cboos** [seattlerb/minitest#789]
I've been surprised to be able to trigger a MRI crash from my minitest code.
It was a simple mistake on my side, doing a `return` from within an `after { ... }`  block.
It also happens when the `return` is placed inside a `before` block.

```
$ cat spec/minitest_crash.rb
require 'minitest/autorun'
require 'minitest/spec'

describe 'a simple crash reproducer' do
  before { return }
  it 'checks stuff' do
  end
end
```

In older (2.2) or more recent (2.6) Rubies, it's correctly reported as a mistake:

```
$ ruby -v
ruby 2.2.5p319 (2016-04-26 revision 54774) [x64-mingw32]

$ ruby spec/minitest_crash.rb
$ ruby spec/minitest_crash.rb
Run options: --seed 38844

# Running:

E

Finished in 0.005171s, 193.3974 runs/s, 0.0000 assertions/s.

  1) Error:
a simple crash reproducer#test_0001_checks stuff:
LocalJumpError: unexpected return
    spec/minitest_crash.rb:6:in `block (2 levels) in <main>'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips

# Switching to 2.6

$ ruby -v
ruby 2.6.0p0 (2018-12-25 revision 66547) [x64-mingw32]

$ ruby spec/minitest_crash.rb
Run options: --seed 45324

# Running:

spec/minitest_crash.rb: unexpected return
```

Whereas both Ruby 2.4 and Ruby 2.5 crash in the `Minitest.autorun` `at_exit` handler:

```
$ ruby -v
ruby 2.4.2p198 (2017-09-14 revision 59899) [x64-mingw32]

$ ruby spec/minitest_crash.rb
Run options: --seed 33380

# Running:

spec/minitest_crash.rb: unexpected return
D:/Workspace/install/windows64/ruby-2.4/lib/ruby/gems/2.4.0/gems/minitest-5.10.3/lib/minitest.rb:60: [BUG] Segmentation fault
ruby 2.4.2p198 (2017-09-14 revision 59899) [x64-mingw32]

-- Control frame information -----------------------------------------------
c:0003 p:---- s:0011 e:000010 CFUNC  :exit
c:0002 p:0027 s:0006 e:000005 BLOCK  D:/Workspace/install/windows64/ruby-2.4/lib/ruby/gems/2.4.0/gems/minitest-5.10.3/lib/minitest.rb:60 [FINISH]
c:0001 p:0000 s:0003 E:000520 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
D:/Workspace/install/windows64/ruby-2.4/lib/ruby/gems/2.4.0/gems/minitest-5.10.3/lib/minitest.rb:60:in `block (2 levels) in autorun'
D:/Workspace/install/windows64/ruby-2.4/lib/ruby/gems/2.4.0/gems/minitest-5.10.3/lib/minitest.rb:60:in `exit'
[...]

# Switching to 2.5

$ ruby -v
ruby 2.5.0p0 (2017-12-25 revision 61468) [x64-mingw32]

$ ruby spec/minitest_crash.rb
Run options: --seed 63376

# Running:

spec/minitest_crash.rb: unexpected return
D:/Workspace/install/windows64/ruby-2.5/lib/ruby/gems/2.5.0/gems/minitest-5.10.3/lib/minitest.rb:60: [BUG] Segmentation fault
ruby 2.5.0p0 (2017-12-25 revision 61468) [x64-mingw32]

-- Control frame information -----------------------------------------------
c:0003 p:---- s:0011 e:000010 CFUNC  :exit
c:0002 p:0022 s:0006 e:000005 BLOCK  D:/Workspace/install/windows64/ruby-2.5/lib/ruby/gems/2.5.0/gems/minitest-5.10.3/lib/minitest.rb:60 [FINISH]
c:0001 p:0000 s:0003 E:002290 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
D:/Workspace/install/windows64/ruby-2.5/lib/ruby/gems/2.5.0/gems/minitest-5.10.3/lib/minitest.rb:60:in `block (2 levels) in autorun'
D:/Workspace/install/windows64/ruby-2.5/lib/ruby/gems/2.5.0/gems/minitest-5.10.3/lib/minitest.rb:60:in `exit'
[...]

```

The bug was most likely fixed in Ruby itself, since the minitest 5.11.3 version that ship with it has the same code as 5.10.3 for the problematic method and doesn't crash.

If you think it's not worth finding a workaround in minitest itself to avoid the crash, feel free to close the bug, but I thought it would be nice to have at least the crash documented somewhere.

**Comment by cboos** [comment]
I just tested the same thing on Linux with Ruby 2.5.0p0, same crash, so it's not Windows specific.

**Comment by zenspider** [comment]
Thank you. Any C level crash with pure ruby is considered a bug in ruby itself. Please file a bug on bugs.ruby-lang.org and link to it here.

I'll poke when I have time, but I doubt there are any safeguards I can put into place.

**Comment by zenspider** [comment]
Anything?

**Comment by cboos** [comment]
Sorry, somehow I wasn't notified of your answers.

I just created [Bug #15766](https://bugs.ruby-lang.org/issues/15766), and it this occasion tried with a few more versions (2.3 also still works, latest 2.4 and 2.5 from rubyinstaller.org still have the crash).

**Comment by MSP-Greg** [comment]
I saw the message in Ruby Core, and checked it with a MinGW 2.5.5 build, and did not have the SEGV.  Haven't done a Ruby 2.4 build...

**Comment by zenspider** [comment]
Thank you for linking to a bug report.

I'm closing this as this isn't really something I can prevent.
