### ISSUE TITLE
Possible to test module in rails?

### ISSUE THREAD

**Issue by Danissss** [seattlerb/minitest#838]
Hi, I have this ruby module at `app/helpers/contents_helper.rb`
```Ruby
module ContentsHelper
  def display_range(range)
     number_with_precision(range)
  end
end
```

I tried to write the test with minitest at `test/helpers/contents_helper_test.rb`, with command `ruby -Ilib:test test/helpers/contents_helper_test.rb`
```Ruby
require 'test_helper'
class ContentsHelperTest < ActionView::TestCase
  describe ContentsHelper do
    describe "test display_range" do
      result = ContentsHelper.display_range(0)
      assert_equal 0, result
    end
  end
end
```

I got error `undefined method `display_range' for nil:NilClass`

After I include the helper
```Ruby
require 'test_helper'
include ContentsHelper
class ContentsHelperTest < ActionView::TestCase
  describe ContentsHelper do
    describe "test display_range" do
      result = ContentsHelper.display_range(0, 1, 0, 1, "mg/100g")
      assert_equal 0, result
    end
  end
end
```

I got `undefined method number_with_precision for nil:NilClass`, which make sense because I didn't include the module or class that define the function `number_with_precision`.

Here is my `test_helper.rb`
```Ruby

require 'minitest/autorun'
require 'minitest/spec'


ENV['RAILS_ENV'] ||= 'test'
require File.expand_path('../../config/environment', __FILE__)
require 'rails/test_help'

class ActiveSupport::TestCase
  # Setup all fixtures in test/fixtures/*.yml for all tests in alphabetical order.
  #
  # Note: You'll currently still have to declare fixtures explicitly in integration tests
  # -- they do not yet inherit this setting
  fixtures :all

  # Add more helper methods to be used by all tests here...
end

```

**Comment by blowmage** [comment]
Lots going on in this question. First, this repo isn't the right place for questions like this. Try StackOverflow instead.

With this test file:

```ruby
require 'test_helper'

class ContentsHelperTest < ActionView::TestCase
  def test_display_range
    result = ContentsHelper.display_range(0)
    assert_equal 0, result
  end
end
```

I get the following failure:

```
$ rails test
Running via Spring preloader in process 83654
Run options: --seed 59799

# Running:

E

Error:
ContentsHelperTest#test_display_range:
NoMethodError: undefined method `display_range' for ContentsHelper:Module
    test/helpers/contents_helper_test.rb:5:in `test_display_range'


rails test test/helpers/contents_helper_test.rb:4



Finished in 0.202643s, 4.9348 runs/s, 0.0000 assertions/s.
1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

If I change the test to this:

```ruby
require 'test_helper'

class ContentsHelperTest < ActionView::TestCase
  include ContentsHelper

  def test_display_range
    result = display_range(0)
    assert_equal 0, result
  end
end
```

Then I resolve the error, but get this error:

```
$ rails test
Running via Spring preloader in process 83654
Run options: --seed 59799

# Running:

E

Error:
ContentsHelperTest#test_display_range:
NoMethodError: undefined method `display_range' for ContentsHelper:Module
    test/helpers/contents_helper_test.rb:5:in `test_display_range'


rails test test/helpers/contents_helper_test.rb:4



Finished in 0.202643s, 4.9348 runs/s, 0.0000 assertions/s.
1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
(base) ☣ [tmp_app:rails6] $ rails test
Running via Spring preloader in process 83696
Run options: --seed 645

# Running:

F

Failure:
ContentsHelperTest#test_display_range [/Users/mrmoore/codez/tmp_app/test/helpers/contents_helper_test.rb:8]:
--- expected
+++ actual
@@ -1 +1,3 @@
-0
+# encoding: ASCII-8BIT
+#    valid: true
+"0.000"



rails test test/helpers/contents_helper_test.rb:6



Finished in 0.632406s, 1.5813 runs/s, 1.5813 assertions/s.
1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
```

If I change the test to this:

```ruby
require 'test_helper'

class ContentsHelperTest < ActionView::TestCase
  include ContentsHelper

  def test_display_range
    result = display_range(0)
    assert_equal "0.000", result
  end
end
```

Then I get a passing test:

```
$ rails test
Running via Spring preloader in process 83732
Run options: --seed 27870

# Running:

.

Finished in 0.174702s, 5.7240 runs/s, 5.7240 assertions/s.
1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by blowmage** [comment]
Another problem with your code is that you are not using the Spec DSL correctly. A `describe` block will not run a test. If you install a gem like `minitest-rails` you could then write your helper test like this:

```ruby
require 'test_helper'

describe ContentsHelper, :helper do
  it "calls display_range" do
    result = display_range(0)
    value(result).must_equal "0.000"
  end
end
```

**Comment by Danissss** [comment]
Thanks!
